- name: instalar apache
  yum: 
   name: httpd
   state: present
  
- name: parar firewalld
  service:
   name: firewalld
   state: stopped

- name: subir apache
  service:
   name: httpd 
   state: started 
